site_name: Generative Network Models Toolbox
theme:
  name: material 
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src] 
          options:
            docstring_style: google
            parse_references: true   # Enable Sphinx-style :class:, :func:, etc.
            show_source: true
            show_root_heading: true
            heading_level: 2

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - docs/javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - User Guide: user-guide.md
  - Examples scripts:
    - Overview: examples/index.md
  - API Reference: 
    - Overview: api-reference/index.md
    - Generative Network Model: api-reference/generative-network-model.md
    - Generative Rules: api-reference/generative-rules.md
    - Optimisation Criteria: api-reference/optimisation-criteria.md
