site_name: Generative Network Models Toolbox
theme:
  name: material 
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [GenerativeNetworkModels]  # Update this to where your Python code lives
          options:
            show_source: false  # Hide source code links
            show_root_heading: true
            heading_level: 2
            docstring_style: google  # Or 'numpy' if you prefer NumPy style

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - User Guide: user-guide.md
  - API Reference: 
    - Overview: api-reference/index.md
    - Generative Network Model: api-reference/generative-network-model.md
    - Generative Rules: api-reference/generative-rules.md
    - Optimisation Criteria: api-reference/optimisation-criteria.md
